Discord:
    discord.token: ['OTU0MzM2OTE0ODMwNDEzODI1.YjRpgw.5bgx2767SUxbnQThgvpeghQGiQo']
  - IncludeReplyToUser: true
    IncludeRetweet: true
    IncludeUserReply: true
    webhook_urls: ['https://discordapp.com/api/webhooks/123456/XXXXXX']
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
     - 'python'
    webhook_urls:
     - 'https://discordapp.com/api/webhooks/123456/XXXXXX'
